# Array

In [1]:
import numpy as np
a=np.array([45,26,75])

In [2]:
a

array([45, 26, 75])

In [4]:
b=np.array([[45,34,56],[54,56,87],[56,87,89]])
b

array([[45, 34, 56],
       [54, 56, 87],
       [56, 87, 89]])

In [6]:
b.shape

(3, 3)

In [9]:
c=np.array([1,2,3])
c.shape

(3,)

In [10]:
b.size

9

In [11]:
c.size

3

In [12]:
b.ndim

2

In [13]:
c.ndim

1

In [14]:
b[0]

array([45, 34, 56])

In [15]:
b[2]

array([56, 87, 89])

In [16]:
c[0]

1

In [17]:
b[2][1]

87

In [18]:
b[0][2]

56

In [19]:
max(b[1])

87

In [20]:
min(b[1])

54

In [22]:
len(b[1])

3

In [23]:
b[:,2]

array([56, 87, 89])

In [26]:
b[:,0].max()

56

In [30]:
b[:,0].min()

45

In [31]:
b[0,:]

array([45, 34, 56])

In [32]:
b[0].sum()

135

In [33]:
b.sum()

564

In [34]:
b.sum(axis=0)

array([155, 177, 232])

In [35]:
b.sum(axis=1)

array([135, 197, 232])

In [36]:
b

array([[45, 34, 56],
       [54, 56, 87],
       [56, 87, 89]])

In [37]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
d[0][1]

array([4, 5, 6])

In [41]:
d[0][0][0]

1

# Arange()

In [54]:
for i in range(1,11):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 

In [56]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.arange(1.0,5.5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [63]:
for i in range(0,10,0.5):
    print(i,end=' ')

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

* zero matrix

In [72]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [77]:
e=np.array([[14,15,16,17,18],[20,30,40,50,60]])
e

array([[14, 15, 16, 17, 18],
       [20, 30, 40, 50, 60]])

In [78]:
m=np.tile(5,[2,5])
m

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [79]:
f=m+e
f

array([[19, 20, 21, 22, 23],
       [25, 35, 45, 55, 65]])

In [80]:
g=np.array([[1,10,4],[2,5,7],[3,4,8]])
g

array([[ 1, 10,  4],
       [ 2,  5,  7],
       [ 3,  4,  8]])

In [81]:
np.linalg.inv(g)

array([[ 0.35294118, -1.88235294,  1.47058824],
       [ 0.14705882, -0.11764706,  0.02941176],
       [-0.20588235,  0.76470588, -0.44117647]])

In [82]:
np.linalg.eig(g)

(array([14.63694242+0.j        , -0.31847121+1.49045818j,
        -0.31847121-1.49045818j]),
 array([[ 5.81039844e-01+0.j        ,  9.19640983e-01+0.j        ,
          9.19640983e-01-0.j        ],
        [ 5.53798270e-01+0.j        ,  8.78547320e-04+0.1968055j ,
          8.78547320e-04-0.1968055j ],
        [ 5.96406050e-01+0.j        , -3.05326408e-01-0.14934213j,
         -3.05326408e-01+0.14934213j]]))

# Random

In [83]:
np.random.random(10)

array([0.14336682, 0.16261034, 0.79859987, 0.37774169, 0.96349301,
       0.58648329, 0.78921917, 0.42763018, 0.31907248, 0.60385493])

In [87]:
np.random.random(1,10)

TypeError: random() takes at most 1 positional argument (2 given)

In [93]:
np.random.randint(100)

31

In [106]:
np.random.randint(10,30)

14

In [107]:
np.random.randint(10,20,30)

array([13, 14, 14, 10, 15, 16, 19, 13, 17, 18, 19, 17, 17, 12, 18, 19, 13,
       17, 17, 15, 10, 18, 14, 12, 16, 14, 11, 15, 14, 14])

In [108]:
np.random.randint(10,25,[5,6])

array([[22, 21, 20, 18, 21, 14],
       [10, 23, 14, 23, 11, 10],
       [12, 24, 21, 12, 18, 10],
       [15, 24, 14, 11, 23, 21],
       [11, 20, 15, 18, 20, 18]])

In [109]:
np.random.rand(10)

array([0.116562  , 0.23948819, 0.08908248, 0.06198972, 0.58275266,
       0.15044069, 0.93971117, 0.56689539, 0.47144838, 0.43364133])

In [116]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [117]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [118]:
np.arange(1,25).reshape(2,3,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])